CREATE TABLE clients (
    documentid VARCHAR2(4000) NOT NULL,
    name       VARCHAR2(4000) NOT NULL,
    phone      NUMBER(11) NOT NULL
);

ALTER TABLE clients ADD CONSTRAINT clients_pk PRIMARY KEY ( documentid );

CREATE TABLE invoices (
    invoice_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    total_amount       NUMBER NOT NULL,
    date_invoice             DATE NOT NULL,
    clients_documentid VARCHAR2(4000) NOT NULL
);


ALTER TABLE invoices
MODIFY total_amount DEFAULT 0;

ALTER TABLE invoices ADD CONSTRAINT invoices_pk PRIMARY KEY ( invoice_id );

ALTER TABLE invoices MODIFY (invoice_id GENERATED AS IDENTITY START WITH 1);

CREATE TABLE invoices_products (
    invoices_invoice_id NUMBER NOT NULL,
    products_product_id NUMBER NOT NULL
);

ALTER TABLE invoices_products ADD CONSTRAINT invoices_productd_pk PRIMARY KEY ( invoices_invoice_id,
                                                                                products_product_id );

CREATE TABLE products (
    product_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name        VARCHAR2(4000) NOT NULL,
    description VARCHAR2(4000)
);

ALTER TABLE products ADD (price NUMBER NOT NULL);


ALTER TABLE products
MODIFY description DEFAULT 'Producto nuevo;';

ALTER TABLE products MODIFY (product_id GENERATED AS IDENTITY START WITH 1);

ALTER TABLE products ADD CONSTRAINT products_pk PRIMARY KEY ( product_id );

ALTER TABLE invoices
    ADD CONSTRAINT invoices_clients_fk FOREIGN KEY ( clients_documentid )
        REFERENCES clients ( documentid );

ALTER TABLE invoices_products
    ADD CONSTRAINT invoices_productd_invoices_fk FOREIGN KEY ( invoices_invoice_id )
        REFERENCES invoices ( invoice_id );

ALTER TABLE invoices_products
    ADD CONSTRAINT invoices_productd_products_fk FOREIGN KEY ( products_product_id )
        REFERENCES products ( product_id );
        
