CREATE TABLESPACE SOLU LOGGING
DATAFILE 'C:\oracleXE\oradata\XE\Soluthev\DATA.dbf' SIZE 1M
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE SOLU_IDX LOGGING DATAFILE 
'C:\oracleXE\oradata\XE\Soluthev\DATA_IDX.dbf' SIZE 1M 
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER Soluthev 
PROFILE DEFAULT IDENTIFIED BY 
123 DEFAULT TABLESPACE 
SOLU TEMPORARY TABLESPACE 
TEMP ACCOUNT UNLOCK;

GRANT CONNECT TO Soluthev;
GRANT RESOURCE TO Soluthev;
ALTER USER Soluthev QUOTA UNLIMITED ON SOLU;
